name: final_project
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  line_awesome_flutter: ^2.0.0
  flutter_screenutil: ^5.9.0
  animated_theme_switcher: ^2.0.8
  flutter_svg: ^2.0.7
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  cached_network_image: ^3.2.3
  scroll_loop_auto_scroll: ^0.0.5
  font_awesome_flutter: ^10.3.0
  flutter_staggered_grid_view: ^0.7.0
  

flutter:
  uses-material-design: true
  assets:
    - assets/


  fonts:
    - family: SFProText
      fonts:
        - asset: assets/fonts/SF-Pro-Text-Thin.otf
          weight: 100
        - asset: assets/fonts/SF-Pro-Text-Regular.otf
          weight: 400
        - asset: assets/fonts/SF-Pro-Text-Medium.otf
          weight: 500
        - asset: assets/fonts/SF-Pro-Text-Bold.otf
          weight: 700